/**
    https://spring.io/guides/gs/managing-transactions/
 */
package com.example.investrest.services;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

import com.example.investrest.models.Quote;
import com.example.investrest.repositories.QuoteRepository;

import java.lang.Iterable;

@Service
public class QuoteService {

    // This means to get the bean called quoteRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private QuoteRepository quoteRepository;

    public Iterable<Quote> findAllQuotes() {
        return quoteRepository.findAll();
    }

    public void saveQuote(Quote quote) {
        quoteRepository.save(quote);
    }
}