/**
    https://spring.io/guides/gs/managing-transactions/
 */
package com.example.investrest.services;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;

import com.example.investrest.models.Quote;
import com.example.investrest.models.Stock;
import com.example.investrest.dto.QuoteDTO;
import com.example.investrest.repositories.QuoteRepository;

import java.lang.Iterable;

@Service
public class QuoteService {

    private static final Logger log = LoggerFactory.getLogger(QuoteService.class);

    // This means to get the bean called quoteRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private QuoteRepository quoteRepository;

    public Iterable<Quote> findAllQuotes() {
        return quoteRepository.findAll();
    }

    public Quote findOneQuote(String stockId) {
        return quoteRepository.findByStockId(stockId);
    }

    public boolean inStock(String stockId, Stock[] stocks){
        // Find if stockId is in the stocks
        for (Stock stock : stocks) {
            String id = stock.getId().toUpperCase();
            if (id.equals(stockId)) {
                return true;
            }
        }

        return false;
    }

    public Quote saveQuote(QuoteDTO quoteDTO, Stock[] stocks) {

        String stockId = quoteDTO.getStockId();

        // Check if should save quote.
        if (!inStock(stockId, stocks)){
            log.info(stockId + ": not valid.");
            return null;
        }

        Quote auxQuote = quoteRepository.findByStockId(stockId);

        if(auxQuote == null){
            // Quote does not exist in the DB.
            auxQuote = quoteDTO.createQuote();
        }else{
            // Quote exists in the DB.
            auxQuote.getQuotes().put(quoteDTO.getDate(), quoteDTO.getPrice());
        }
        quoteRepository.save(auxQuote);

        return auxQuote;
    }
}
